### PR TITLE
Fix list handling in getObjectCustomProperty(); closes #9

### LINKED ISSUE #9: wrapper function setWebContainerCustomProperty
The function setWebContainerCustomProperty() is a wrapper for setCustomPropertyOnObject(). I noticed that setWebContainerCustomProperty() does not correctly update web container custom properties that already exist. This occurs when there are more than one property. For instance:

setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.foo", "abc123")
setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.bar", "asdf")

setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.foo", "xyz890")
setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.bar", "jkl;")

will result in the creation of a second instance of properties com.ibm.ws.webcontainer.foo and com.ibm.ws.webcontainer.bar.

The problem occurs because setWebContainerCustomProperty() uses getObjectCustomProperty() which is not correctly creating a list object from showAttribute(object_id,'properties'). Specifically, within getObjectCustomProperty():

    x = AdminConfig.showAttribute(object_id,'properties')[1:-1]
    if len(x) == 0:
        return None  # no properties set yet

This is code is checking for '[]' that represents an empty list. However, this causes the if-statement,

    if x.startswith("["):
        propsidlist = x[1:-1].split(' ')

to never return 'True'. Therefore, the split(' ') never gets run to discover the second property contained in x.

I can provide my version of getObjectCustomProperty(object_id, propname) if anyone is interested.

Lastly, is there any difference in using setWebContainerCustomProperty() versus createWebContainerProp()?

### PR DESCRIPTION
**Pull request by gpoul**

### CODE REVIEW

**Comment by dekuntz** [comment]
I think this should be merged to wsadminlib.

**Comment by dekuntz** [comment]
I have a question. The function getObjectCustomProperty() seems to assume that:
```python
AdminConfig.showAttribute(object_id,'properties')
```
will always return a string representation of a List. However, the comments and FIXME suggest that sometimes .showAttribute() will return a value without the enclosing "[]".

Have you seen an example of this?

If so, then perhaps this would handle that condition:

```python
def getObjectCustomProperty(object_id, propname):
    x = AdminConfig.showAttribute(object_id,'properties')
    #print "value of properties attribute=%s" % x
    # This can be of the format "[foo(value) bar(baz)]" where the values are "foo(value)",
    # "bar(baz)".  It also seems to be able to be just "foo(value)"
    if x.startswith('[') and x.endswith(']'):
        propsidlist = _splitlist(x)
    else:
        propsidlist = [x]
    #print "List of properties = %s" % repr(propsidlist)
    if len(propsidlist[0]) == 0:
        return None # No properties set yet. _splitlist(x) returned [''].
    for id in propsidlist:
        #print "id=%s" % id
        name = AdminConfig.showAttribute(id, 'name')
        if name == propname:
            return AdminConfig.showAttribute(id, 'value')
    return None
```

**Comment by gpoul** [comment]
@dekuntz I changed as little code as possible in my change. Your proposed use of _splitlist(x) definitely improves readability, but I'm a little nervous in changing this without being very sure we're not breaking anything. The case where showAttribute() returns a value without the enclosing brackets should already be covered by the existing function as well in line 5435: https://github.com/wsadminlib/wsadminlib/pull/10/files#diff-cd459ed2db4a6d8573a3347b9ca5d414L5435

**Comment by dekuntz** [comment]
@gpoul I understand. I appreciate your feedback.
I'm looking into whether AdminConfig.showAttribute(object_id,'properties') always returns a list represented as a string. I believe this is true when the attribute is 'properties'.

If so then this works:

```python
def getObjectCustomProperty(object_id, propname):
    #propsidlist = getObjectAttribute(object_id,'properties') #'properties' attributes are always lists
    # Using AdminUtilities.convertToList() instead of _splitlist() because returns
    # [''] on an input of '[]'.
    propsidlist = AdminUtilities.convertToList(AdminConfig.showAttribute(object_id,'properties'))
    for id in propsidlist:
        #print "id=%s" % id
        name = AdminConfig.showAttribute(id, 'name')
        if name == propname:
            return AdminConfig.showAttribute(id, 'value')
    else:
        return None
 ```

**Comment by wsadminlib** [comment]
I wish wsadminlib had a thorough test suite which would allow us to accept pervasive low-level changes like this with confidence.  If anyone writes more tests, please consider contributing them to wsadminlib.tests.py.

**Pull request merged**
